### ISSUE TITLE
Improve error message when Python executable is not found.

### ISSUE THREAD

**Issue by limiteinductive** [Glyphack/enderpy#223]
Hey,

Upon executing `enderpy check test.py` command, an error occurred: `Error: × No such file or directory (os error 2)`.

This was confusing because `tokenize` and `parse` worked properly with the same file. After inspecting the code and trying to debug, it turns out that I had no Python executable installed 😅

Wouldn't it be helpful for CLI users to have more explicit error messages?

(disclaimer: I don't know how to Rust)
```rust
fn get_python_executable() -> Result<PathBuf, String> {
    match std::process::Command::new("python")
        .arg("-c")
        .arg("import sys; print(sys.executable)")
        .output()
    {
        Ok(output) => {
            let path = String::from_utf8(output.stdout)
                .map_err(|_| "Failed to parse Python executable path".to_string())?;
            Ok(PathBuf::from(path.trim()))
        }
        Err(_) => Err("Python is not installed or not found in the system PATH".to_string()),
    }
}
```

**Comment by Glyphack** [comment]
Hey,
yes the error messages need to be improved. I'm focusing on the tool itself at the moment that's why you see unexpected errors and crashes in some cases using the CLI.
Honestly the python executable is not even needed right now, The type checker is using typeshed at the moment so the error you getting is completely useless.

I'll clean up and improve the error handling in the next commits. In case you want to do this yourself, I can help you out in discord. There's not a lot of stuff to learn before you can write Rust.
